[metadata]
title = "Mahou-Shoujo Sakura-San!" # title of the game
author = "starrrosie" # author(s) of the game
description = "" # description of the game
version = "0.1.0" # current version, obeying semver
icons = { ctr = "game/icon.png"} # custom icon paths

[build]
targets = ["ctr"]
source = "game"
packaged = true